# Generated by Django 4.2.7 on 2023-11-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='content',
        ),
    ]
